### ISSUE TITLE
[FEATURE SUGGESTION] Bulk Download Js Hacks

### ISSUE THREAD

**Issue by scollovati** [AllTheDucks/jshack-v1#5]
It would be great if there is a bulk download option.
It may be very useful when backing up environment configurations.

**Comment by shaneargo** [comment]
Hi @scollovati,

That sounds like a quite useful function. I'll be honest though, it is unlikely we'll have time to implement it in the near term. 

I'll leave it open for anyone who wants to have a go at it. Otherwise, hopefully we'll get a chance at some point to include this function.

Cheers,
Shane.

**Comment by scollovati** [comment]
No more relevant since Blackboard will deprecate third party B2s.

**Comment by T3chShaman** [comment]
Okay thanks
